### PR TITLE
Reduce app's database hits, and refactor

### PR DESCRIPTION
**Pull request by mileswwatkins**
This turns each view into just one or two database queries, instead of one per `Job`. Hopefully, this'll speed up Moxie in production, and permit us to move all of our Open States jobs there.
:us: :fireworks:

@paultag, let me know what changes I need to make to get this up to snuff! First time using `asyncio`, so let me know if I've broken any rules or best-practices.

### CODE REVIEW

**Comment by mileswwatkins** [comment]
Thowin' a bone to https://github.com/paultag/moxie/issues/67.

**Comment by paultag** [comment]
Love it. This is awesome. Thank you, @mileswwatkins !

**Comment by paultag** [comment]
Totally cleans up the code, no changes needed :)

**Comment by mileswwatkins** [comment]
@paultag, when you get a chance, could you let me know how deployment to the Moxie machine works? The plethora of Dockerization therein has me a bit flummoxed, I feel like I'm _just_ missing something :)

**Pull request merged**
