### PR TITLE
Dramatically improve Jobs-based view performance

### PR DESCRIPTION
**Pull request by mileswwatkins**
Ditched the ORM and switched to RawSQL:tm: with a fancy subquery to improve performance; @rshorey  is going to be so proud when she sees this. Now, we don't read _every single_ `Run` from the database, just the ones that we need!

Currently Sunlight's Moxie views are busted on `502`s and `504`s; I thought I'd tested this away by dumping tons and tons of fake `Jobs` into my local database, but apparently I didn't put enough in there to simulate production :)

### CODE REVIEW

**Comment by paultag** [comment]
Yeah, this ORM is totally busted.

Nice.

**Comment by mileswwatkins** [comment]
Bleh, [another Docker build failure](https://registry.hub.docker.com/u/paultag/moxie/builds_history/41518/). I'll do some testing on my end.

**Comment by paultag** [comment]
Hunh, it's failing with 'You must put some 'source' URIs in your
sources.list'

Don't we do that? /me checks

On Thu, Aug 6, 2015 at 3:23 PM, Miles Watkins <notifications@github.com>
wrote:

> Bleh, another Docker build failure
> <https://registry.hub.docker.com/u/paultag/moxie/builds_history/41518/>.
> I'll do some testing on my end.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paultag/moxie/pull/74#issuecomment-128479948>.
>



-- 
:wq

**Comment by paultag** [comment]
(https://registry.hub.docker.com/u/paultag/moxie/build_id/12343/code/b6vvuhudebdudieqbh8fted/ link to the log)

**Comment by paultag** [comment]
cc @tianon - we have source in these suckers, is the docker base image
doing something to us here?

On Thu, Aug 6, 2015 at 3:27 PM, Paul R. Tagliamonte <paultag@gmail.com>
wrote:

> Hunh, it's failing with 'You must put some 'source' URIs in your
> sources.list'
>
> Don't we do that? /me checks
>
> On Thu, Aug 6, 2015 at 3:23 PM, Miles Watkins <notifications@github.com>
> wrote:
>
>> Bleh, another Docker build failure
>> <https://registry.hub.docker.com/u/paultag/moxie/builds_history/41518/>.
>> I'll do some testing on my end.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/paultag/moxie/pull/74#issuecomment-128479948>.
>>
>
>
>
> --
> :wq
>



-- 
:wq

**Comment by mileswwatkins** [comment]
@paultag: I was looking for the log :)
Unfortunately, I don't currently have permissions to access. Can you add me somehow? Username is `mileswwatkins`.

**Comment by mileswwatkins** [comment]
Since I switched to `stable`/`jessie`, I stopped getting those `sources.list` errors when testing yesterday. Before I switched, I got them spuriously on maybe 1/3 of all my runs of `docker build --no-cache .`.

**Comment by mileswwatkins** [comment]
Just completed three successful Docker builds locally; I'll work more on this once I can view the Docker Hub error log.

**Comment by paultag** [comment]
Got a build to pass off my phone :)

**Comment by mileswwatkins** [comment]
:confetti_ball:! Thanks so much. What did you do differently?

Just deployed, and some of the views now work. But the performance is still sorta junk! For example, the `/jobs/` endpoint is still so slow it gives `5xx`s. Is this something that some work on https://github.com/paultag/moxie/issues/66 could fix? Or would you suspect it's something else? I'm available to knock this out, since I consider it crucial to OS deployment.

**Comment by paultag** [comment]
On Fri, Aug 07, 2015 at 08:12:55AM -0700, Miles Watkins wrote:
>    [1]:confetti_ball:! Thanks so much. What did you do differently?

Nothing, I just kept kicking it off. Something's fucked with the
builder. cc @tianon - know about this?

>    Just deployed, and some of the views now work. But the performance is
>    still sorta junk! For example, the /jobs/ endpoint is still so slow it
>    gives 5xxs. Is this something that some work on [2]#66 could fix? Or would
>    you suspect it's something else? I'm available to knock this out, since I
>    consider it crucial to OS deployment.

Hurm, not sure. It'll likely need to be profiled. Perhaps check postgres
logs?

Also, this changeset introduced a security vuln. SQL injection. If I hit
jobs for the user ID "TRUE; DELETE FROM Jobs; --", I'll blow away the DB


We need to be a lot more careful if we're using raw SQL


-- 
<paul/>

**Comment by mileswwatkins** [comment]
Damn, you're right about the injection, I'll think about a way to quash that.

Also, I just made the fake `run.log` values in my local setup waaaaay longer (`UPDATE run SET log=repeat('foobar', 500000);`) to mimic the size of production logs, which appropriately slowed down my local setup. I think I know a simple way to get around this lag now.

PR coming after lunch for these :)

**Pull request merged**
